spring:
  thymeleaf:
    cache: false
  data:
    mongodb:
      uri: "mongodb://rootuser:rootpass@localhost:27018/plataforma-integracao?authSource=admin"

betha:
  auth:
    oauth:
      client:
        id: "xxxxxxxxxxxxxxxxx"
        secret_id: "xxxxxxxxxxxxx"
        redirect: "http://localhost:8080/callback"
        scopes: "contas-usuarios.suite,user-accounts.suite"
  services:
    login: "https://login.betha.cloud/servicelogin"
    oauth: "https://plataforma-oauth.betha.cloud/auth/oauth2"
    usuarios: "https://plataforma-autorizacoes.betha.cloud/user-accounts/v0.1/api"
  tributos:
    url: "https://tributos.suite.betha.cloud/dados/v1/"
    accessToken: "Bearer xxxxxxxxxxxxxxxxxxxxxxxx"
    userAccess: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  cadastro-unico:
    url: "https://plataforma-cadastro-unico.betha.cloud/api/v2/"
    accessToken: "xxxx"