version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: plataforma_integracao_mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
volumes:
  mongo_data:
