spring:
  thymeleaf:
    cache: false
  data:
    mongodb:
      uri: "mongodb+srv://tempbethacon:9nfaS4zTHVCELAWL@test-plat-cluster-mongo.1ppxy.mongodb.net/temp-bethacon"

betha:
  auth:
    oauth:
      client:
        id: "34bf8868-b799-4dea-9eaf-8fa327572423"
        secret_id: "3fdd79d3-a121-43a6-b2ce-1914372e8d24"
        redirect: "http://localhost:8080/callback"
        scopes: "contas-usuarios.suite,user-accounts.suite"
  services:
    login: "https://service-login.cloud.betha.com.br/servicelogin"
    oauth: "https://oauth.cloud.betha.com.br/auth/oauth2"
    usuarios: "https://useraccounts.cloud.betha.com.br/user-accounts/v0.1/api"
  tributos:
    url: "https://tributos.suite.betha.cloud/dados/v1/"
    accessToken: "Bearer d85b1677-19e2-4007-9bd8-c21087b83d4b"
    userAccess: "v-FNuBejwK_L_wdSIOB4-6KD9IEj6zj8b7pP7YotynI="
  cadastro-unico:
    url: "https://plataforma-cadastro-unico.betha.cloud/api/v2/"
    accessToken: "xxxx"
